# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build: .
    image: axum-matching-engine-server
    container_name: axum-matching-engine-server-1
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    command: ["java", "-cp", "app.jar:quickfixj-all-2.3.1.jar", "exchange.core2.core.FixEngine"]

    #  quickfixj:
    #    build: ./axum-matching-engine
    #    image: quickfixj-container
    #    container_name: quickfixj-server-1
    #    ports:
    #      - "5000:5000"
    #    depends_on:
    #      - server
    #
    #  # Example backend service (update as needed)
    #  backend:
    #    image: backend-service-image
    #    build:
    #      context: ./backend
    #    container_name: backend-server-1
    #    ports:
    #      - "8081:8081"
    #    depends_on:
    #      - quickfixj
    #
    #  # Example web service (update as needed)
    #  web:
    #    image: web-interface-image
    #    build:
    #      context: ./web
    #    container_name: web-server-1
    #    ports:
    #      - "8082:8082"
    #    depends_on:
    #      - backend

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

